# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
# Uncomment this line if you're using Swift


use_frameworks!

pod 'AFNetworking', '~> 2.5'
pod 'BDBOAuth1Manager'
pod 'Firebase', '>= 2.5.0'
pod 'SwiftQRCode'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

#target 'Punchit' do
#pod 'AFNetworking'
#pod 'BDBOAuth1Manager'
#end

#target 'PunchitTests' do

#end

#target 'PunchitUITests' do

#end

